// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesx-ISB7rOdEuj054-EbBu9AQ7n8fT44',
    appId: '1:615781815052:web:4dc87454bcfb7151f26f29',
    messagingSenderId: '615781815052',
    projectId: 'beatflow-569d0',
    authDomain: 'beatflow-569d0.firebaseapp.com',
    storageBucket: 'beatflow-569d0.appspot.com',
    measurementId: 'G-HH31C0L8C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDt6_y2EfIlmltIusADEB1PguwKP1g1I',
    appId: '1:615781815052:android:2735665628b560e6f26f29',
    messagingSenderId: '615781815052',
    projectId: 'beatflow-569d0',
    storageBucket: 'beatflow-569d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDucIUZh-NrtGq5GzgmP4JnhX2dRFXBGg8',
    appId: '1:615781815052:ios:e0795ea1e28c347df26f29',
    messagingSenderId: '615781815052',
    projectId: 'beatflow-569d0',
    storageBucket: 'beatflow-569d0.appspot.com',
    iosBundleId: 'com.example.beatflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDucIUZh-NrtGq5GzgmP4JnhX2dRFXBGg8',
    appId: '1:615781815052:ios:1947521368f8d65ef26f29',
    messagingSenderId: '615781815052',
    projectId: 'beatflow-569d0',
    storageBucket: 'beatflow-569d0.appspot.com',
    iosBundleId: 'com.example.beatflow.RunnerTests',
  );
}
